runtime: nodejs20

handlers:
- url: /(.*\..+)$ 
  static_files: dist/seacewebapp/browser/\1
  upload: dist/seacewebapp/browser/(.*\..+)$

- url: /.*
  secure: always
  static_files: dist/seacewebapp/browser/index.html
  upload: dist/seacewebapp/browser/index.html